version: "3"

networks:
  java-grpc-net:
    driver: bridge

services:
  java-grpc-sink:
    image: 'ofertaviv/java-grpc-sink:latest'
    networks:
      - java-grpc-net
    ports:
      - '8123:8123'
    environment:
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure

  java-grpc-propagator:
    image: 'ofertaviv/java-grpc-propagator:latest'
    networks:
      - java-grpc-net
    ports:
      - '8122:8122'
    environment:
      - JAVA_GRPC_HTTP_SINK_HOST=java-grpc-sink
      - JAVA_GRPC_HTTP_SINK_PORT=8123
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure

  java-grpc-http-entry-point:
    image: 'ofertaviv/java-grpc-http-entry-point:latest'
    networks:
      - java-grpc-net
    ports:
      - '8121:8121'
    environment:
      - JAVA_GRPC_HTTP_PROPAGATOR_HOST=java-grpc-propagator
      - JAVA_GRPC_HTTP_PROPAGATOR_PORT=8122
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure
